/* Career Combine — hand-tuned careers.
   These are written and adjusted by hand. Every other U.S. occupation comes from
   careers-bls.js, which is generated from BLS and O*NET data by tools/build-careers.mjs.
   soc: the BLS occupation codes (SOC) this career covers. Generated careers with those
   codes are folded into this one, and its card shows their official BLS numbers.
   rel: for broad careers, specific BLS occupations in the same family. They stay separate
   careers with their own numbers; the broad career's card lists them with their fit. */
"use strict";
/* ============================================================
   CAREER POOL — demand levels (0–1) + facts. pay = [entry, ~yr 4, senior] in $k, rough U.S. figures
   (OTE for commission roles). edu: 0 none · 1 cert/associate · 2 bachelor's · 3 graduate/license
   ============================================================ */
const CAREERS_HAND=[
 {id:"se",soc:["41-9031"],n:"Sales / Solutions Engineer",r:"EIS",pay:[95,160,240],d:{c:.35,tr:.4,s:.65,cu:.9,l:.4,au:.65,v:.7,p:.65,da:.4,th:.3,rp:.45,h:.6,o:.4,w:.4,pr:.9,en:.2,pu:.3},ease:"Medium",ai:"Low–Med",trv:"15–30%",wlb:"Mixed",edu:2,start:"Associate Solutions Engineer",end:"Director of Solutions Engineering",titles:"Associate Sales Engineer, Solutions Consultant, Pre-Sales Engineer",step:"1–2 years in technical support or implementation at a software company, then move over.",sk:["presenting","troubleshooting","sales","customer","product","communication"],ind:"tech software saas"},
 {id:"impl",n:"Implementation Consultant",r:"SCI",pay:[65,100,150],d:{c:.25,tr:.35,s:.2,cu:.85,l:.4,au:.55,v:.65,p:.6,da:.45,th:.35,rp:.1,h:.6,o:.45,w:.5,pr:.65,pu:.35},ease:"Easy",ai:"Medium",trv:"0–30%",wlb:"Mixed",edu:1,start:"Implementation Specialist",end:"Director of Professional Services",titles:"Implementation Specialist, Onboarding Specialist, Implementation Consultant",step:"Frame past work as rolling out systems and training people on them.",sk:["training","customer","pm","documentation","troubleshooting"],ind:"tech software healthcare education"},
 {id:"csm",n:"Customer Success / Account Manager",r:"SEC",pay:[60,95,160],d:{c:.1,tr:.2,s:.45,cu:1,l:.35,au:.55,v:.55,p:.5,da:.35,th:.15,rp:.3,h:.45,o:.2,w:.4,pr:.7,pu:.4},ease:"Easy",ai:"Med–High",trv:"5–20%",wlb:"Good",edu:1,start:"Customer Success Associate",end:"VP of Customer Success",titles:"Customer Success Associate, Account Manager, Client Success Specialist",step:"Lead with customer-facing results: retention, satisfaction scores, upsells.",sk:["customer","communication","crm","training","troubleshooting"],ind:"tech software saas"},
 {id:"sales",soc:["41-4011","41-3091"],n:"Sales (SDR → Account Executive)",r:"ESC",pay:[65,140,250],d:{c:0,tr:.25,s:1,cu:.9,l:.35,au:.6,v:.55,p:.9,da:.2,th:.05,rp:.95,h:.7,o:.2,en:.4,w:.3,pr:.8,pu:.2},ease:"Easy",ai:"Med–High",trv:"0–30%",wlb:"Demanding",edu:0,start:"Sales Development Representative",end:"VP of Sales",titles:"Sales Development Rep, Business Development Rep, Account Executive",step:"Pick an industry you know and pitch your background to companies that sell into it.",sk:["sales","negotiation","crm","communication","customer","presenting"],ind:"tech medical saas sports"},
 {id:"revops",n:"Revenue / Sales Operations",r:"CEI",pay:[70,110,170],d:{c:.4,tr:.05,s:.35,cu:.45,l:.5,au:.6,v:.5,p:.55,da:.85,th:.1,rp:.15,h:.5,o:.1,w:.4,pr:.5,pu:.2},ease:"Medium",ai:"Medium",trv:"0–5%",wlb:"Good",edu:2,start:"Sales Operations Analyst",end:"VP of Revenue Operations",titles:"Sales Operations Analyst, Revenue Operations Analyst, CRM Analyst",step:"Salesforce Administrator certification plus one sample sales dashboard.",sk:["crm","excel","dataviz","sql","process"],ind:"tech saas"},
 {id:"data",rel:["15-2041","15-1243","13-1161"],n:"Data / BI Analyst",r:"ICE",pay:[65,95,150],d:{c:.65,tr:.05,s:0,cu:.3,l:.25,au:.6,v:.45,p:.45,da:1,th:.1,rp:.05,h:.45,o:.05,w:.4,pr:.45,pu:.3},ease:"Medium",ai:"High",trv:"0–5%",wlb:"Good",edu:2,start:"Junior Data Analyst",end:"Director of Analytics",titles:"Data Analyst, Reporting Analyst, Business Intelligence Analyst",step:"Learn SQL plus Power BI or Tableau and publish one dashboard on public data.",sk:["sql","excel","bi","dataviz","python","stats"],ind:"sports healthcare finance retail tech"},
 {id:"ds",soc:["15-2051"],n:"Data Scientist / ML",r:"ICA",pay:[95,140,210],d:{c:.9,tr:.05,s:0,cu:.2,l:.25,au:.7,v:.5,p:.5,da:1,th:.05,rp:.05,h:.5,o:.05,w:.5,pr:.45,pu:.35},ease:"Hard",ai:"Medium",trv:"0–5%",wlb:"Good",edu:3,start:"Data Analyst (first)",end:"Head of Data Science",titles:"Data Scientist, Machine Learning Engineer, Quantitative Analyst",step:"Start as an analyst and build two public modeling projects in Python.",sk:["python","stats","ml","sql","math"],ind:"tech sports finance healthcare"},
 {id:"swe",soc:["15-1252"],n:"Software Developer",r:"IRC",pay:[80,130,200],d:{c:1,tr:.05,s:0,cu:.2,l:.3,au:.7,v:.5,p:.55,da:.5,th:.2,rp:.05,h:.6,o:.1,w:.35,pr:.3,en:.3,pu:.3},ease:"Medium",ai:"Med–High",trv:"0–5%",wlb:"Good",edu:1,start:"Junior Developer",end:"Staff Engineer / Engineering Manager",titles:"Junior Software Developer, Web Developer, Software Engineer I",step:"Ship 2–3 real projects on GitHub; bootcamp or CS degree both work.",sk:["programming","git","python","cloud"],ind:"tech gaming sports"},
 {id:"cyber",soc:["15-1212"],n:"Cybersecurity Analyst",r:"ICR",pay:[75,115,170],d:{c:.45,tr:.1,s:0,cu:.35,l:.3,au:.55,v:.6,p:.75,da:.6,th:.4,rp:.05,h:.6,o:.3,w:.5,pr:.3,pu:.5},ease:"Medium",ai:"Low–Med",trv:"0–10%",wlb:"Mixed",edu:1,start:"SOC Analyst",end:"Security Engineer / CISO",titles:"SOC Analyst, Security Analyst, Cybersecurity Specialist",step:"Help-desk experience plus CompTIA Security+.",sk:["security","networking","linux","troubleshooting","scripting"],ind:"tech government finance healthcare"},
 {id:"grc",soc:["13-1041"],n:"GRC / Compliance Analyst",r:"CIE",pay:[65,100,160],d:{c:.1,tr:.1,s:.05,cu:.45,l:.4,au:.55,v:.4,p:.45,da:.55,th:.1,rp:.05,h:.45,o:.15,w:.8,pr:.45,pu:.4},ease:"Medium",ai:"Low–Med",trv:"0–10%",wlb:"Good",edu:2,start:"GRC / IT Compliance Analyst",end:"Director of GRC",titles:"GRC Analyst, IT Compliance Analyst, Risk Analyst",step:"An entry security cert (Security+) plus any audit, policy, or compliance work you've done.",sk:["compliance","risk","documentation","security","excel"],ind:"finance healthcare government tech"},
 {id:"itsup",soc:["15-1232","15-1244"],n:"IT Support → Systems Admin",r:"RCI",pay:[45,75,130],d:{c:.25,tr:.15,s:0,cu:.75,l:.35,au:.45,v:.6,p:.6,da:.3,th:.8,rp:.05,h:.5,o:.7,w:.35,pr:.3,pu:.4},ease:"Easy",ai:"Medium",trv:"Low",wlb:"Mixed",edu:0,start:"Help Desk Technician",end:"IT Manager / IT Director",titles:"Help Desk Technician, IT Support Specialist, Desktop Support",step:"CompTIA A+ gets most people in the door.",sk:["troubleshooting","endpoint","networking","customer"],ind:"education healthcare tech"},
 {id:"cloud",rel:["15-1241","15-1244","15-1299"],n:"Cloud / DevOps Engineer",r:"IRC",pay:[85,135,200],d:{c:.75,tr:.05,s:0,cu:.2,l:.3,au:.6,v:.5,p:.7,da:.4,th:.4,rp:.05,h:.65,o:.1,w:.4,pr:.25,pu:.2},ease:"Hard",ai:"Medium",trv:"0–5%",wlb:"Mixed",edu:1,start:"Cloud Support Associate",end:"Principal Engineer",titles:"Cloud Support Associate, Junior DevOps Engineer, Systems Engineer",step:"Sysadmin or support experience plus an AWS or Azure associate cert.",sk:["cloud","linux","scripting","networking"],ind:"tech"},
 {id:"ba",soc:["15-1211"],n:"Business Systems Analyst",r:"CIS",pay:[65,95,140],d:{c:.25,tr:.1,s:.05,cu:.6,l:.35,au:.5,v:.45,p:.45,da:.7,th:.15,rp:.05,h:.4,o:.2,w:.7,pr:.5,pu:.3},ease:"Easy",ai:"Med–High",trv:"0–10%",wlb:"Good",edu:2,start:"Business Analyst I",end:"Director of Business Systems",titles:"Business Analyst, Business Systems Analyst, Systems Analyst",step:"SQL basics plus a before/after process map of something you improved.",sk:["requirements","process","excel","sql","documentation"],ind:"healthcare finance tech"},
 {id:"pm",rel:["11-2021","11-3021","15-1211"],n:"Product Manager",r:"EIA",pay:[95,150,250],d:{c:.25,tr:.1,s:.25,cu:.65,l:.7,au:.75,v:.8,p:.7,da:.65,th:.1,rp:.1,h:.7,o:.2,en:.4,w:.7,pr:.75,pu:.4},ease:"Hard",ai:"Low–Med",trv:"0–10%",wlb:"Mixed",edu:2,start:"Associate Product Manager",end:"VP of Product",titles:"Associate Product Manager, Product Analyst, Product Owner",step:"Start as a BA, analyst, or in customer success, then ask to own a small feature.",sk:["product","requirements","communication","dataviz","leadership"],ind:"tech gaming sports"},
 {id:"proj",soc:["13-1082"],n:"Project / Program Manager",r:"ECS",pay:[60,95,150],d:{c:.05,tr:.1,s:.1,cu:.6,l:.85,au:.5,v:.55,p:.65,da:.45,th:.15,rp:.05,h:.55,o:.35,w:.6,pr:.65,pu:.35},ease:"Easy",ai:"Medium",trv:"0–10%",wlb:"Mixed",edu:1,start:"Project Coordinator",end:"PMO Director",titles:"Project Coordinator, Junior Project Manager, Program Coordinator",step:"CAPM certification and lead one project end to end at your current job.",sk:["pm","communication","leadership","budgeting","documentation"],ind:"construction healthcare tech"},
 {id:"ux",soc:["15-1255"],n:"UX / Product Designer",r:"AIS",pay:[70,110,170],d:{c:.2,tr:.05,s:.15,cu:.5,l:.35,au:.65,v:.65,p:.55,da:.45,th:.1,rp:.05,h:.5,o:.15,w:.5,pr:.6,pu:.5},ease:"Hard",ai:"Medium",trv:"0–5%",wlb:"Good",edu:1,start:"Junior UX Designer",end:"Design Director",titles:"UX Designer, Product Designer, UI Designer",step:"A 3-project portfolio with real case studies, not just screenshots.",sk:["ux","design","research","presenting"],ind:"tech gaming"},
 {id:"mkt",soc:["13-1161"],n:"Digital Marketing",r:"AEI",pay:[50,80,140],d:{c:.1,tr:.15,s:.45,cu:.5,l:.4,au:.6,v:.75,p:.6,da:.55,th:.05,rp:.15,h:.55,o:.2,w:.75,pr:.6,en:.3,pu:.35},ease:"Easy",ai:"High",trv:"0–15%",wlb:"Mixed",edu:1,start:"Marketing Coordinator",end:"Chief Marketing Officer",titles:"Marketing Coordinator, Digital Marketing Specialist, Social Media Specialist",step:"Grow one account or run a small campaign and report the numbers.",sk:["marketing","social","writing","dataviz","design"],ind:"sports entertainment retail"},
 {id:"writer",soc:["27-3043","27-3031"],n:"Writer / Communications",r:"ASE",pay:[45,70,120],d:{c:0,tr:.1,s:.15,cu:.3,l:.2,au:.8,v:.6,p:.55,da:.15,th:0,rp:.1,h:.5,o:.15,w:1,pr:.4,en:.3,pu:.55},ease:"Medium",ai:"High",trv:"0–10%",wlb:"Good",edu:1,start:"Content Writer",end:"Communications Director",titles:"Content Writer, Copywriter, Communications Specialist",step:"Publish five strong writing samples on one topic.",sk:["writing","communication","research","social"],ind:"media nonprofit"},
 {id:"media",soc:["27-1024","27-4021","27-4032"],n:"Video, Photo & Graphic Design",r:"ARE",pay:[40,65,110],d:{c:.05,tr:.35,s:.2,cu:.45,l:.25,au:.8,v:.8,p:.65,da:.05,th:.6,rp:.3,h:.65,o:.55,w:.3,pr:.4,en:.55,pu:.45},ease:"Medium",ai:"High",trv:"10–40%",wlb:"Mixed",edu:0,start:"Production Assistant / Junior Designer",end:"Creative Director",titles:"Video Editor, Graphic Designer, Photographer, Content Creator",step:"Build a reel or portfolio of 6–8 strong pieces.",sk:["media","design","social","marketing"],ind:"media entertainment sports"},
 {id:"fin",soc:["13-2051"],n:"Financial Analyst",r:"CIE",pay:[65,100,160],d:{c:.25,tr:.05,s:.1,cu:.3,l:.35,au:.5,v:.45,p:.65,da:.95,th:0,rp:.15,h:.65,o:.15,w:.45,pr:.55,pu:.2},ease:"Medium",ai:"Medium",trv:"0–5%",wlb:"Mixed",edu:2,start:"Financial Analyst",end:"CFO",titles:"Financial Analyst, FP&A Analyst, Investment Analyst",step:"Advanced Excel modeling; finance or accounting coursework helps.",sk:["finance","excel","accounting","budgeting","dataviz"],ind:"finance"},
 {id:"acct",soc:["13-2011"],n:"Accountant / Auditor",r:"CEI",pay:[55,85,140],d:{c:.05,tr:.1,s:0,cu:.35,l:.3,au:.45,v:.3,p:.6,da:.85,th:0,rp:.05,h:.6,o:.2,w:.35,pr:.25,pu:.25},ease:"Medium",ai:"High",trv:"0–15%",wlb:"Mixed (busy season)",edu:2,start:"Staff Accountant",end:"Controller / CFO",titles:"Staff Accountant, Audit Associate, Bookkeeper",step:"Accounting coursework; the CPA opens the top-paying doors.",sk:["accounting","excel","compliance","finance"],ind:"finance"},
 {id:"advisor",soc:["13-2052"],n:"Financial Advisor / Banker",r:"ESC",pay:[50,110,220],d:{c:0,tr:.15,s:.85,cu:.95,l:.3,au:.85,v:.55,p:.65,da:.45,th:0,rp:.8,h:.6,o:.3,en:.6,w:.25,pr:.65,pu:.5},ease:"Medium",ai:"Low–Med",trv:"0–15%",wlb:"Mixed",edu:1,start:"Personal Banker / Advisor Trainee",end:"Practice Owner",titles:"Financial Advisor Trainee, Personal Banker, Insurance Agent",step:"Pass the SIE exam and land a trainee program at a bank or firm.",sk:["sales","finance","communication","crm"],ind:"finance"},
 {id:"ops",soc:["13-1081"],n:"Operations / Supply Chain",r:"ECR",pay:[55,85,140],d:{c:.05,tr:.2,s:.15,cu:.55,l:.8,au:.5,v:.65,p:.75,da:.55,th:.45,rp:.1,h:.7,o:.75,w:.3,pr:.45,pu:.3},ease:"Easy",ai:"Medium",trv:"0–20%",wlb:"Demanding",edu:1,start:"Operations Coordinator",end:"VP of Operations",titles:"Operations Coordinator, Logistics Analyst, Supply Chain Analyst, Shift Supervisor",step:"Fix one bottleneck where you work and measure the time or money saved.",sk:["operations","process","leadership","excel","pm"],ind:"manufacturing retail logistics healthcare sports"},
 {id:"hr",soc:["13-1071"],n:"HR / Recruiter",r:"SEC",pay:[50,80,130],d:{c:0,tr:.1,s:.45,cu:.95,l:.45,au:.5,v:.55,p:.55,da:.3,th:0,rp:.2,h:.5,o:.4,w:.5,pr:.6,pu:.55},ease:"Easy",ai:"Med–High",trv:"0–15%",wlb:"Good",edu:1,start:"Recruiting Coordinator / HR Assistant",end:"Head of People",titles:"Recruiter, HR Generalist, Recruiting Coordinator",step:"Agency recruiting hires for drive; the aPHR helps for HR roles.",sk:["recruiting","hr","communication","training"],ind:"tech healthcare"},
 {id:"teach",soc:["25-2021","25-2022","25-2031"],n:"Teacher",r:"SAE",pay:[45,60,85],d:{c:0,tr:0,s:.15,cu:1,l:.7,au:.5,v:.65,p:.6,da:.25,th:.2,rp:0,h:.6,o:1,w:.45,pr:.9,pu:1},ease:"Medium",ai:"Low",trv:"None",wlb:"Mixed",edu:2,start:"Substitute / Paraprofessional",end:"Principal / District Leader",titles:"Teacher, Substitute Teacher, Paraprofessional",step:"Substitute or work as a para to test it; most states require a license.",sk:["teaching","curriculum","presenting","communication"],ind:"education sports"},
 {id:"idtrain",soc:["25-9031","13-1151"],n:"Instructional Designer / Trainer",r:"ASI",pay:[60,85,120],d:{c:.1,tr:.15,s:.1,cu:.55,l:.4,au:.65,v:.6,p:.45,da:.3,th:.1,rp:.05,h:.45,o:.15,w:.75,pr:.75,pu:.65},ease:"Medium",ai:"Med–High",trv:"0–20%",wlb:"Good",edu:2,start:"Corporate Trainer",end:"Director of Learning",titles:"Instructional Designer, Corporate Trainer, Learning Specialist",step:"Build one short e-learning module as a portfolio piece.",sk:["curriculum","training","writing","design","presenting"],ind:"education healthcare tech"},
 {id:"nurse",soc:["29-1141"],n:"Registered Nurse",r:"SIR",pay:[75,90,120],d:{c:0,tr:.1,s:0,cu:1,l:.5,au:.4,v:.75,p:.95,da:.4,th:.7,rp:0,h:.8,o:1,w:.35,pr:.35,pu:1},ease:"Medium",ai:"Low",trv:"Low (travel nursing optional)",wlb:"Demanding",edu:2,start:"CNA (to test it) → RN",end:"Nurse Practitioner / Nurse Manager",titles:"Registered Nurse, LPN, Nursing Assistant",step:"Start CNA training to test the fit; an ADN or BSN gets you to RN.",sk:["healthcare","communication","customer"],ind:"healthcare"},
 {id:"allied",rel:["29-2034","29-2032","29-2010","29-1126","29-2055","29-1292"],n:"Allied Health Technologist",r:"RSI",pay:[50,70,95],d:{c:.05,tr:.05,s:0,cu:.85,l:.25,au:.45,v:.5,p:.7,da:.35,th:.85,rp:0,h:.5,o:1,w:.2,pr:.2,pu:.85},ease:"Medium",ai:"Low",trv:"None",wlb:"Good",edu:1,start:"Technologist / Technician",end:"Lead Technologist / Department Manager",titles:"Radiologic Technologist, Respiratory Therapist, Surgical Tech, PT Assistant",step:"Most are 2-year programs with strong job placement.",sk:["healthcare","handson","customer"],ind:"healthcare"},
 {id:"hadmin",soc:["11-9111"],n:"Healthcare Admin / Health IT",r:"CSE",pay:[55,85,140],d:{c:.1,tr:.05,s:.05,cu:.6,l:.55,au:.45,v:.5,p:.6,da:.6,th:.15,rp:.05,h:.5,o:.6,w:.5,pr:.45,pu:.75},ease:"Medium",ai:"Medium",trv:"0–10%",wlb:"Good",edu:2,start:"Patient Access Rep / Clinic Coordinator",end:"Health System Director",titles:"Clinic Coordinator, Health Information Specialist, Practice Manager",step:"Front-desk or patient-access jobs are the usual door in.",sk:["healthcare","operations","compliance","excel"],ind:"healthcare"},
 {id:"counsel",soc:["21-1018","21-1021"],n:"Counselor / Social Worker",r:"SAI",pay:[45,60,85],d:{c:0,tr:.1,s:0,cu:1,l:.3,au:.5,v:.6,p:.7,da:.2,th:0,rp:0,h:.55,o:.85,w:.6,pr:.35,pu:1},ease:"Hard",ai:"Low",trv:"Low",wlb:"Mixed",edu:3,start:"Case Aide / Peer Support",end:"Licensed Therapist / Clinical Director",titles:"Case Manager, School Counselor, Social Worker",step:"Case-aide or peer-support work; licensure needs a master's.",sk:["counseling","communication","documentation"],ind:"healthcare education nonprofit government"},
 {id:"trades",rel:["47-2111","47-2152","49-9021","47-2031","51-4121","49-3023","49-9071","47-2221"],n:"Skilled Trades",r:"RIC",pay:[45,75,110],d:{c:.05,tr:.3,s:.15,cu:.5,l:.4,au:.65,v:.65,p:.6,da:.15,th:1,rp:.05,h:.6,o:1,en:.45,w:.05,pr:.15,pu:.45},ease:"Easy",ai:"Low",trv:"Local",wlb:"Mixed",edu:0,start:"Apprentice",end:"Master / Contractor",titles:"Electrician Apprentice, HVAC Technician, Plumber Apprentice",step:"Apply to a union or employer apprenticeship — you get paid to learn.",sk:["handson","safety","troubleshooting","math"],ind:"construction energy"},
 {id:"eng",rel:["17-2051","17-2141","17-2071","17-2072","17-2112","17-2081"],n:"Engineer (Civil, Mechanical, Electrical)",r:"IRC",pay:[75,105,150],d:{c:.35,tr:.2,s:.05,cu:.35,l:.4,au:.55,v:.55,p:.6,da:.65,th:.65,rp:.05,h:.55,o:.5,w:.55,pr:.4,pu:.45},ease:"Hard",ai:"Low–Med",trv:"0–25%",wlb:"Good",edu:2,start:"Engineer I / Engineering Technician",end:"Principal Engineer",titles:"Engineer I, Engineering Technician, CAD Designer",step:"An accredited engineering degree; technicians can start with a 2-year program.",sk:["engineering","cad","math","pm"],ind:"manufacturing construction energy"},
 {id:"sci",rel:["19-1042","19-2031","19-1029","19-1021","19-2041","19-2012"],n:"Scientist / Researcher",r:"IRA",pay:[55,85,130],d:{c:.4,tr:.1,s:0,cu:.2,l:.3,au:.7,v:.45,p:.45,da:.85,th:.7,rp:0,h:.55,o:.7,w:.75,pr:.45,pu:.6},ease:"Hard",ai:"Low–Med",trv:"0–10%",wlb:"Good",edu:3,start:"Lab Technician / Research Assistant",end:"Principal Scientist",titles:"Research Assistant, Lab Technician, Research Scientist",step:"Lab roles need a science bachelor's; research careers need grad school.",sk:["research","lab","stats","writing"],ind:"healthcare biotech environment"},
 {id:"consult",soc:["13-1111"],n:"Management / Tech Consulting",r:"EIC",pay:[80,130,250],d:{c:.3,tr:.75,s:.35,cu:.85,l:.6,au:.5,v:.9,p:.85,da:.65,th:.1,rp:.2,h:.9,o:.75,w:.75,pr:.85,pu:.3},ease:"Hard",ai:"Medium",trv:"50–80%",wlb:"Demanding",edu:2,start:"Associate Consultant",end:"Partner",titles:"Associate Consultant, Consulting Analyst, Technology Consulting Analyst",step:"Practice case interviews; big firms hire analysts every fall.",sk:["strategy","presenting","excel","communication","research"],ind:"tech healthcare finance sports"},
 {id:"entre",rel:["11-1021","11-9199"],n:"Entrepreneur / Small Business Owner",r:"EAR",pay:[30,80,250],d:{c:.15,tr:.3,s:.85,cu:.85,l:.75,au:1,v:.95,p:.85,da:.45,th:.45,rp:1,h:.9,o:.55,en:1,w:.45,pr:.75,pu:.6},ease:"Medium",ai:"Low",trv:"Varies",wlb:"Demanding",edu:0,start:"Side hustle or freelancing",end:"Business owner",titles:"Self-employed, founder, freelancer",step:"Land three paying customers on the side before you quit anything.",sk:["sales","marketing","budgeting","leadership","operations"],ind:""},
 {id:"sportsbiz",rel:["27-2022","27-2023","13-1011","11-2011"],n:"Sports & Entertainment Business",r:"ESC",pay:[45,70,130],d:{c:.05,tr:.35,s:.6,cu:.85,l:.45,au:.5,v:.8,p:.8,da:.4,th:.3,rp:.45,h:.85,o:.8,w:.4,pr:.7,pu:.75},ease:"Hard",ai:"Low–Med",trv:"Local + events",wlb:"Demanding",edu:1,start:"Ticket Sales Rep / Event Staff",end:"VP of Business Operations",titles:"Inside Sales Rep (team), Partnership Coordinator, Team Operations Assistant",step:"Ticket sales is the classic way in; work game days to build contacts.",sk:["sports","events","sales","marketing","communication"],ind:"sports entertainment music"},
 {id:"event",soc:["13-1121"],n:"Event Planner / Producer",r:"ESA",pay:[45,65,110],d:{c:0,tr:.55,s:.4,cu:.85,l:.65,au:.55,v:.9,p:.9,da:.2,th:.6,rp:.1,h:.85,o:.95,w:.35,pr:.55,pu:.5},ease:"Easy",ai:"Low",trv:"20–60%",wlb:"Demanding",edu:1,start:"Event Coordinator / AV Technician",end:"Director of Events",titles:"Event Coordinator, Event Producer, Venue Coordinator, AV Technician",step:"Work events (venues, conferences, weddings) and track the budgets you handled.",sk:["events","operations","customer","pm"],ind:"sports entertainment hospitality music"},
 {id:"realestate",soc:["41-9022","11-9141"],n:"Real Estate Agent / Property Manager",r:"ESC",pay:[40,80,180],d:{c:0,tr:.3,s:.9,cu:.95,l:.3,au:.9,v:.75,p:.7,da:.35,th:.2,rp:1,h:.75,o:.85,en:.75,w:.25,pr:.65,pu:.4},ease:"Easy",ai:"Low–Med",trv:"Local",wlb:"Demanding",edu:0,start:"Licensed Agent / Leasing Consultant",end:"Broker / Owner",titles:"Real Estate Agent, Leasing Consultant, Property Manager",step:"Get your state license (a few weeks of coursework); expect a slow first year.",sk:["sales","negotiation","customer","marketing"],ind:"real estate housing"},
 {id:"legal",soc:["23-2011"],n:"Paralegal",r:"CIE",pay:[45,62,90],d:{c:0,tr:.1,s:.05,cu:.6,l:.35,au:.45,v:.55,p:.75,da:.45,th:0,rp:.05,h:.6,o:.6,w:.85,pr:.45,pu:.45},ease:"Easy",ai:"Med–High",trv:"0–10%",wlb:"Mixed",edu:1,start:"Legal Assistant",end:"Senior Paralegal / Paralegal Manager",titles:"Paralegal, Legal Assistant, Litigation Paralegal",step:"A paralegal certificate; specializing in one practice area raises pay.",sk:["legal","writing","research","documentation"],ind:"legal government"},
 {id:"attorney",soc:["23-1011"],n:"Attorney",r:"EIS",pay:[70,120,220],d:{c:0,tr:.2,s:.35,cu:.8,l:.6,au:.65,v:.7,p:.85,da:.5,th:0,rp:.1,h:.75,o:.7,w:.95,pr:.85,pu:.65},ease:"Hard",ai:"Medium",trv:"0–20%",wlb:"Demanding (varies a lot by practice area)",edu:3,start:"Law Clerk / Associate Attorney",end:"Partner / Judge",titles:"Associate Attorney, Staff Attorney, Public Defender, Assistant District Attorney",step:"Law school (3 years) and the bar exam. Working as a paralegal first is common and helps admissions.",sk:["legal","writing","research","presenting"],ind:"legal government nonprofit"},
 {id:"ea",soc:["43-6011"],n:"Executive Assistant / Office Manager",r:"CES",pay:[45,65,100],d:{c:0,tr:.15,s:.1,cu:.8,l:.45,au:.45,v:.75,p:.65,da:.45,th:.2,rp:0,h:.55,o:.85,w:.6,pr:.4,pu:.45},ease:"Easy",ai:"High",trv:"Low",wlb:"Good",edu:0,start:"Administrative Assistant",end:"Chief of Staff / Director of Operations",titles:"Administrative Assistant, Executive Assistant, Office Manager",step:"Own one leader's calendar, travel, and projects and become the person they can't work without.",sk:["pm","communication","excel","documentation"],ind:"legal healthcare tech finance"},
 {id:"contracts",rel:["13-1020","13-1041","23-1011"],n:"Contracts Manager",r:"CEI",pay:[60,90,140],d:{c:0,tr:.1,s:.3,cu:.6,l:.4,au:.55,v:.5,p:.65,da:.5,th:0,rp:.05,h:.55,o:.4,w:.85,pr:.45,pu:.3},ease:"Medium",ai:"Med–High",trv:"0–10%",wlb:"Good",edu:1,start:"Contracts Administrator",end:"Director of Contracts",titles:"Contracts Administrator, Contract Specialist, Procurement Specialist",step:"Legal-assistant or purchasing experience plus a contract-management certification (such as NCMA's).",sk:["legal","negotiation","documentation","compliance"],ind:"legal government tech healthcare"},
 {id:"legalops",rel:["23-2011","43-6012","15-1211"],n:"Legal Operations / E-Discovery",r:"CIE",pay:[60,90,140],d:{c:.3,tr:.1,s:.05,cu:.45,l:.4,au:.55,v:.5,p:.65,da:.75,th:.1,rp:.05,h:.6,o:.3,w:.55,pr:.4,pu:.3},ease:"Medium",ai:"Medium",trv:"0–10%",wlb:"Mixed",edu:1,start:"Litigation Support / E-Discovery Specialist",end:"Director of Legal Operations",titles:"Litigation Support Specialist, E-Discovery Analyst, Legal Operations Analyst",step:"Get certified on an e-discovery review platform (Relativity is the big one) and lead with your legal experience.",sk:["legal","documentation","excel","sql"],ind:"legal tech"},
 {id:"policy",rel:["19-3094","19-3011","19-3051","13-1041"],n:"Public Policy / Government Analyst",r:"ISC",pay:[55,80,120],d:{c:.1,tr:.15,s:.1,cu:.5,l:.4,au:.55,v:.6,p:.55,da:.6,th:0,rp:0,h:.5,o:.4,w:.85,pr:.6,pu:.95},ease:"Medium",ai:"Medium",trv:"0–15%",wlb:"Good",edu:2,start:"Program Assistant / Legislative Aide",end:"Policy Director",titles:"Policy Analyst, Program Analyst, Legislative Aide",step:"Write a 2-page brief on a local issue; government and nonprofit boards post entry roles.",sk:["policy","research","writing","dataviz"],ind:"government nonprofit"},
 {id:"fire",soc:["33-2011","29-2042"],n:"Firefighter / EMT / Public Safety",r:"RSE",pay:[45,70,100],d:{c:0,tr:.1,s:0,cu:.8,l:.5,au:.35,v:.85,p:1,da:.1,th:.9,rp:0,h:.85,o:1,w:.15,pr:.25,pu:1},ease:"Medium",ai:"Low",trv:"Local",wlb:"Demanding (shifts)",edu:1,start:"EMT",end:"Captain / Chief",titles:"EMT, Firefighter, Paramedic, Police Officer",step:"EMT-Basic is a one-semester course and opens most public-safety doors.",sk:["healthcare","safety","handson","communication"],ind:"government public safety"},
 {id:"hosp",soc:["11-9051","11-9081"],n:"Hospitality / Restaurant Management",r:"ERS",pay:[40,60,100],d:{c:0,tr:.1,s:.45,cu:1,l:.75,au:.5,v:.8,p:.85,da:.3,th:.55,rp:.3,h:.85,o:1,en:.4,w:.15,pr:.45,pu:.5},ease:"Easy",ai:"Low",trv:"Low",wlb:"Demanding",edu:0,start:"Shift Lead",end:"General Manager / Owner",titles:"Shift Supervisor, Assistant Manager, Front Desk Lead",step:"Ask for shift-lead duties; management-trainee programs hire fast.",sk:["customer","leadership","operations"],ind:"hospitality food travel sports"}
];
